### ISSUE TITLE
NullPointerException in DumpVisitor

### ISSUE THREAD

**Issue by phaensgen** [rpau/javalang#13]
Hi,

when parsing and serializing the code below, I get a NullPointerException:

public enum A
{
    B
    {
    };
}

-->

java.lang.NullPointerException
    at org.walkmod.javalang.visitors.DumpVisitor.printChildrenNodes(DumpVisitor.java:324)
    at org.walkmod.javalang.visitors.DumpVisitor.visit(DumpVisitor.java:2118)
    at org.walkmod.javalang.ast.body.EnumConstantDeclaration.accept(EnumConstantDeclaration.java:88)
    at org.walkmod.javalang.visitors.DumpVisitor.printChildrenNodes(DumpVisitor.java:308)
    at org.walkmod.javalang.visitors.DumpVisitor.visit(DumpVisitor.java:2059)
    at org.walkmod.javalang.ast.body.EnumDeclaration.accept(EnumDeclaration.java:68)
    at org.walkmod.javalang.visitors.DumpVisitor.visit(DumpVisitor.java:765)
    at org.walkmod.javalang.ast.CompilationUnit.accept(CompilationUnit.java:96)
    at org.walkmod.javalang.ast.Node.toString(Node.java:190)
    at ...

There is some null check broken:
         if (previous == null || !(previous instanceof SwitchEntryStmt)) {
            if (!parent.isNewNode()) {
               if (parent.getEndLine() != previous.getEndLine()) {
                  printer.printLn();
               }
            } else {
               printer.printLn();
            }
         }

Previous may be null, so previous.getEndLine will lead to the exception.

FYI

**Comment by rpau** [comment]
Ok, thanks for reporting this issue. I will solve it during ASAP during this week.

**Comment by rpau** [comment]
It has been deployed to the public maven repo with the version 4.2.4
If you are using walkmod, the update will be done automatically :-)
